version: '3'
services:
  mq-host:
    image: ndidplatform/mq-testtools:latest
    ports:
      - "8080:8080"
      - "4444:4444"
    command: bash -c "node mqTestHost 4444"
    networks:
      - mq-testtool
  mq-node1:
    image: ndidplatform/mq-testtools:latest
    ports:
      - "4450:4444"
    command: bash -c "node mqTestNode mq-node1 4444 mq-host 4444"
    networks:
      - mq-testtool
  mq-node2:
    image: ndidplatform/mq-testtools:latest
    ports:
      - "4451:4444"
    command: bash -c "node mqTestNode mq-node2 4444 mq-host 4444"
    networks:
      - mq-testtool
networks:
  mq-testtool: